---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 1.0.5
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

# AC 109
- Author: Bernes Karachai


```{python}
import time
print ("Date run: "  + time.strftime("%x"))
```

# Dataset Used
- Data source: JIRA.csv


# Objective: 


We would like to keep tabs on JIRA workflow and current practices to optimize our planning and execution. The metrics below will establish a baseline. Further metrics may be added to compare one quarter to the next.




# Any Issues:

a) No


```{python}
#######################################
print('Setting working environment...')
#######################################

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.lines as mlines
from matplotlib.lines import Line2D

import matplotlib.ticker as ticker
import matplotlib.cm as cm
import matplotlib as mpl

import matplotlib.pyplot as plt
# %matplotlib inline
#import seaborn as sns


import os
import sys
from datetime import datetime
from datetime import date
from datetime import time
from datetime import timedelta
from termcolor import colored
import time



import seaborn as sns
plt.style.use('ggplot')
pd.options.display.max_rows = 999
pd.options.display.max_columns = 999
pd.options.display.max_colwidth = 999

from IPython.display import HTML as html_print

def cstr(s, color='black'):
    return "<text style=color:{}>{}</text>".format(color, s)


print('done.')
```

```{python}
df=pd.read_csv("data//JIRA.csv")
df.shape
```

```{python}
df.head(1)
```

### keep only completed tasks.

```{python}
df["completed"]=pd.to_datetime(df['Resolved'])
df["started"]=pd.to_datetime(df['Created'])
```

```{python}
df = df.dropna(subset=["completed"]) 
df.shape
```

```{python}
Creator=df.groupby(['Assignee']).size().reset_index().rename(columns={0:'count'}).sort_values(by=['count'])
Creator
```

```{python}
df_aymone=df[df.Assignee =="bernes.karacay.1"]
df_aymone.shape
```

```{python}
df_aymone
```

### Quarterly dates for first run: 7/1/19-9/30/19


keep if resolved dates is between above dates

```{python}
df=df[df.completed >="1/Jul/19"]
df.shape
```

```{python}
#df=df[df.completed <="30/Sep/19"]
#df.shape
```

```{python}
df.head(1)
```

```{python}
Creator=df.groupby(['Assignee']).size().reset_index().rename(columns={0:'count'}).sort_values(by=['count'])
Creator
```

# Metrics Requested


## Completion - excluding ongoing/recurring tickets


Count total tickets closed in previous quarter (excluding ongoing, recurring):

```{python}
df.shape[0]
```

## Percentage tickets closed of those submitted during the quarter

```{python}
df2=pd.read_csv("data//JIRA.csv")

```

```{python}
df2["started"]=pd.to_datetime(df2['Created'])
```

```{python}
df2 = df2.dropna(subset=["started"]) 
df2.shape
```

### Quarterly dates for first run: 7/1/19-9/30/19


keep if resolved dates is between above dates

```{python}
df2=df2[df2.started >="1/Jul/19"]
df2.shape
```

```{python}
# df2=df2[df2.started <="30/Sep/19"]
# df2.shape
```

Percentage tickets closed of those submitted during the quarter

```{python}
round(df.shape[0]/df2.shape[0]*100,0)
```

## Movement  - excluding ongoing/recurring tickets


How long each ticket spent in each stage (mean, median, range).
Sadly we dont have time forready qc, under qc or etc.


### created to updated

```{python}
df["Updated_date"]=pd.to_datetime(df['Updated'])
```

```{python}
df["time_to_updated"]=(df["Updated_date"]-df["started"]).astype('timedelta64[h]')
```

```{python}
df.time_to_updated.describe()
```

### last viewed

```{python}
df["Updated_date"]=pd.to_datetime(df['Updated'])
```

```{python}
df["time_to_updated"]=(df["Updated_date"]-df["started"]).astype('timedelta64[h]')
```

```{python}
df.time_to_updated.describe()
```

### due date

```{python}
df["due_date"]=pd.to_datetime(df['Due date'])
```

```{python}
df["time_due_date"]=(df["due_date"]-df["started"]).astype('timedelta64[h]')
```

```{python}
df.time_due_date.describe()
```

## Efficiency   - excluding ongoing/recurring tickets

```{python}
df["time_to_complete"]=(df["completed"]-df["started"]).astype('timedelta64[h]')
```

```{python}
df.head(1)
```

How long a ticket took from opening to close (Status “Done”) (mean, median, range)

```{python}
df.time_to_complete.describe()

```

### exclude recurring

```{python}
df["RECURRING"]=0
df.loc[df['Summary'].str.contains("RECURRING",case=False),["RECURRING"]]=1
df_no_recurring=df.loc[df['RECURRING'] == 0]
```

```{python}
df_no_recurring.shape
```

How long a ticket took from opening to close (Status “Done”) (mean, median, range)(with out recurring)

```{python}
df_no_recurring.time_to_complete.describe()
```

### How many comments a ticket had, on average - measuring activity/back-and-forth (count)

```{python}
comment_df=df[["Comment","Comment.1","Comment.2","Comment.3","Comment.4","Comment.5","Comment.6","Comment.7","Comment.8","Comment.9","Comment.10","Comment.11","Comment.12","Comment.13","Comment.14","Comment.15","Comment.16","Comment.17","Comment.18","Comment.19","Comment.20","Comment.21","Comment.22","Comment.23","Comment.24","Comment.25","Comment.26","Comment.27","Comment.28","Comment.29","Comment.30","Comment.31","Comment.32","Comment.33","Comment.34","Comment.35","Comment.36","Comment.37","Comment.38","Comment.39","Comment.40","Comment.41","Comment.42","Comment.43","Comment.44","Comment.45","Comment.46","Comment.47","Comment.48","Comment.49"]]
```

```{python}
comment_df.head(1)
```

```{python}
comment_df['full_count'] = comment_df.apply(lambda x: x.count(), axis=1)
```

```{python}
comment_df.head(2)
```

How many comments a ticket had, on average - measuring activity/back-and-forth (count)

```{python}
comment_df.full_count.describe()
```

## Cleanliness  - excluding ongoing/recurring tickets


### How many tickets (count) missing:Due Date

```{python}
df.head(2)

```

```{python}
df["due_date"].isnull().sum()
```

### How many tickets (count) missing:Open Date

```{python}
df["Created"].isnull().sum()
```

### How many tickets (count) missing:Custom field (Lead Analyst)

```{python}
df["Custom field (Lead Analyst)"].isnull().sum()
```

### How many tickets (count) missing:Assignee

```{python}
df["Assignee"].isnull().sum()
```

### How many tickets (count) missing:Reporter

```{python}
df["Reporter"].isnull().sum()
```

### How many tickets (count) missing:Notebook


We cannot categorize attacment


## Most common requesters - include all tickets from previous quarter

```{python}
df=pd.read_csv("data//JIRA.csv")
```

```{python}
Creator=df.groupby(['Creator']).size().reset_index().rename(columns={0:'count'}).sort_values(by=['count'])
Creator
```

```{python}

```

## Most common types of requests - include all tickets from previous quarter


Organize by ticket title tag first - count how many Ad Hoc, how many recurring, etc. - include any tickets opened or moved during that quarter


### recurring

```{python}
df["RECURRING"]=0
```

```{python}

df.loc[df['Summary'].str.contains("RECURRING",case=False),["RECURRING"]]=1
```

```{python}
df["RECURRING"].sum(skipna = True) 
```

### Ad Hoc

```{python}
df["AdHoc"]=0
```

```{python}

df.loc[df['Summary'].str.contains("Ad Hoc",case=False),["AdHoc"]]=1
```

```{python}
df["AdHoc"].sum(skipna = True) 
```

### CDR

```{python}
df["CDR"]=0
```

```{python}

df.loc[df['Summary'].str.contains("CDR ",case=False),["CDR"]]=1
```

```{python}
df["CDR"].sum(skipna = True) 
```

### RDR

```{python}
df["RDR"]=0
```

```{python}

df.loc[df['Summary'].str.contains("RDR",case=False),["RDR"]]=1
```

```{python}
df["RDR"].sum(skipna = True) 
```

### Data pull

```{python}
df["Data pull"]=0
```

```{python}

df.loc[df['Summary'].str.contains("Data pull",case=False),["Data pull"]]=1
```

```{python}
df["Data pull"].sum(skipna = True) 
```

## Busy season - use all tickets since the inception of the board


One version with recurring/ongoing tickets included

```{python}
df["started"]=pd.to_datetime(df['Created'])
df["started1"]=df.started.map(lambda x: x.strftime('%Y-%m-%d'))
df['started1'] = pd.to_datetime(df['started1'], errors='coerce')
```

```{python}
graph_table=(df['started1'].sub(pd.to_timedelta(df['started1'].dt.dayofweek, unit='D'))
    .value_counts(sort=False)).reset_index().rename(columns={'started1':'count','index':'time'}).sort_values(by=['time'])
graph_table
```

```{python}
graph_table.plot.line(x = 'time', y = 'count')
```

One version WITHOUT recurring/ongoing tickets included

```{python}
df["RECURRING"]=0
```

```{python}

df.loc[df['Summary'].str.contains("RECURRING"),["RECURRING"]]=1
```

```{python}
df_nore=df[df.RECURRING != 1]
```

```{python}
df_nore["started"]=pd.to_datetime(df_nore['Created'])
df_nore["started1"]=df_nore.started.map(lambda x: x.strftime('%Y-%m-%d'))
df_nore['started1'] = pd.to_datetime(df_nore['started1'], errors='coerce')
```

```{python}
graph_table=(df_nore['started1'].sub(pd.to_timedelta(df_nore['started1'].dt.dayofweek, unit='D'))
    .value_counts(sort=False)).reset_index().rename(columns={'started1':'count','index':'time'}).sort_values(by=['time'])
graph_table
```

```{python}
graph_table.plot.line(x = 'time', y = 'count')
```

```{python}

```
